version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    container_name: db-api-lespattes
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - demo-network
networks:
  demo-network:
    external: false
    name: "demo-network"